{% set name = "django-allauth" %}
{% set version = "65.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_allauth-{{ version }}.tar.gz
  sha256: 1a564fd2f5413054559078c2b7146796b517c1e7a38c6312e9de7c9bb708325d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.8.0
    - pip
  run:
    - python >={{ python_min }}
    - django >=4.2
    - asgiref >=3.8.1

test:
  imports:
    - allauth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pennersr/django-allauth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  description: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  doc_url: https://django-allauth.readthedocs.io/en/latest/
  dev_url: https://github.com/pennersr/django-allauth

extra:
  recipe-maintainers:
    - rxm7706
    - jacksund
    - cshaley
    - sannykr
