{% set name = "django-allauth" %}
{% set version = "0.58.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40ad5c2ae78757261fc1628a94bb67416f91565f578e592d5906948b59682a5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - django >=2.0
    - python3-openid >=3.0.8
    - requests-oauthlib >=0.3.0
    - requests

test:
  imports:
    - allauth
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pennersr/django-allauth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  description: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  doc_url: https://django-allauth.readthedocs.io/en/latest/
  dev_url: https://github.com/pennersr/django-allauth

extra:
  recipe-maintainers:
    - rxm7706
    - jacksund
    - cshaley
    - sannykr
