{% set name = "django-allauth" %}
{% set version = "0.45.0" %}
{% set sha256 = "6d46be0e1480316ccd45476db3aefb39db70e038d2a543112d314b76bb999a4e" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - django >=1.11
    - python3-openid >=3.0.8
    - requests-oauthlib >=0.3.0
    - requests

about:
  home: https://github.com/pennersr/django-allauth
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  description: Integrated set of Django applications addressing authentication, registration, account management as well as 3rd party (social) account authentication
  doc_url: https://django-allauth.readthedocs.io/en/latest/
  dev_url: https://github.com/pennersr/django-allauth

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
